{
    "name": "OpenCart 3 Connector 2020",
    "summary": "OpenCart 3 Connector 2020",
    "version": "14.0.1.0.0",
    "author": "Unicoding.by",
    "website": "https://unicoding.by",
    "license": "AGPL-3",
    'category': 'Connectors',
    "depends": ["base", "sale", "crm", "purchase", "stock", "delivery", "unicoding_integrations"],
    'data':[
            'data/unicoding_integrations.xml',
            'views/unicoding_integrations.xml',
            'views/sale_view.xml',
            'views/res_partner_view.xml',
            'views/crm_lead_views.xml'
    ],
    "price": 199.99,
    'currency': 'EUR',
    'images': [
        'static/description/banner.png',
        'static/description/banner1.png',
        'static/description/icon.png',
        'static/description/integration.png',
        'static/description/Screenshot_1.png',
        'static/description/Screenshot_2.png',
        'static/description/Screenshot_3.png',
        'static/description/Screenshot_4.png',
        'static/description/Screenshot_5.png',
        'static/description/Screenshot_6.png',
        'static/description/Screenshot_7.png',
        'static/description/Screenshot_8.png',
        'static/description/Screenshot_9.png',
        'static/description/Screenshot_10.png',
        'static/description/Screenshot_11.png',
        'static/description/Screenshot_12.png',
        'static/src/img/opencart.png',
    ],
    'installable': True,
    'application': True,
}
